### ISSUE TITLE
css changes not appearing on site

### ISSUE THREAD

**Issue by zleonska** [semanticdata/zola-minimal#2]
Hi, 
It didn't take me long to get out of my depth and with something I thought I understood. When you get a chance could you look at this css entries for <hr>  for me? The code seems okay but nothing is changing on my local site.  Other css adjustments have been attained.  I am just missing something; I can't quite pinpoint what it is.

hr 
Minor changes to the original css hr block to not reflect on the site.
It isn't exactly what I was looking for ... I went down a rabbit hole attempting to change the line! It is from old css which works in my original html5. but not in main.css

hr {
	width: 75%;
	height: 4px;
	display: block;
	margin-top: 30px;
	margin-bottom: 50px;
	border: none;
	background-color: #990000;
	}

Thank-you so much for your theme on Zola. This is as close as I have ever come to getting a working static site!  I have much to learn about how things work, but I am having fun.

Zuzanna

**Comment by semanticdata** [comment]
Hi, Zuzanna,

Sorry for the delay in replying. Are you trying to restyle the `<hr>` element in your website? If that's the case you should be changing the `sass/_base.scss` file. Especifically these lines [here](https://github.com/semanticdata/zola-minimal/blob/dac6d3b166503cdbe4299aee5b901dc09ed61362/sass/_base.scss#L94C1-L99C2).

Change:

```css
hr {
  border: 0;
  background: #e5e5e5;
  height: 1px;
  margin: 0 0 20px;
}
```

To your desired:

```css
hr {
  width: 75%;
  height: 4px;
  display: block;
  margin-top: 30px;
  margin-bottom: 50px;
  border: none;
  background-color: #990000;
}
```

Let me know if that helps!

**Comment by zleonska** [comment]
No worries taking the time to respond, my life moves at a slow pace!

Replacing the hr [   in _base.scss work well.   Thank-you.

It was my understanding that any changes to css should go in _custom.sccs  to preserve changes if theme is updated.  What is the best practice for adding my cosmetic changes to your theme.

Hope your day is filled with sunshine and happy coding
Zuzanna

**Comment by semanticdata** [comment]
Hmm, you are correct. I didn't try the changes inside `sass/_custom.css`. Here's how I got it working:

1. Removed the line with `generate_feed = false` from `config.toml` (This is an older Zola version option. I need to update the theme for newer Zola versions.)
2. Added your styles to `sass/_custom.scss` so it looks like this:

```scss
// Custom CSS code goes here

hr {
    width: 75%;
    height: 4px;
    display: block;
    margin-top: 30px;
    margin-bottom: 50px;
    border: none;
    background-color: #990000;
}
```

3. Using the latest version of [Zola](https://www.getzola.org/) 0.20.0 I started the site with `zola serve`.

The `<hr>` appeared to be affected by your styles.

Here's the before:

![Image](https://github.com/user-attachments/assets/16095a4f-5c0c-42dc-9755-32c4f7781827)

And after:

![Image](https://github.com/user-attachments/assets/ce2e994f-eb2b-44fe-97d2-43f913fcb79f)

Let me know if this works for you, or if this is what's not causing any changes to appear on your site. If that's the case, do you care to share your code/repo with me so I can take a look at it? Maybe run it myself?

Thanks!
